### ISSUE TITLE
Enzyme UI-test fails

### ISSUE THREAD

**Issue by stami** [root-two/react-native-drawer#170]
Hi!

I use Mocha and Enzyme to test my app, but for some reason, UI-tests fail if there is react-native-drawer imported.

Here's how I run the tests

```
mocha --require react-native-mock/mock --compilers js:babel-core/register --recursive test/ui
```

My test file. (Other ui-tests run fine, it's just this library)

```
import React from 'react';
import { View } from 'react-native';
import { shallow } from 'enzyme';
import { expect } from 'chai';

import Drawer from 'react-native-drawer'; // It fails here. Anything below doesn't matter

describe('Drawer', () => {
  it('it should render', () => {
    const wrapper = shallow(
      <Drawer
        type="overlay"
        content={<View />}
        tapToClose
        openDrawerOffset={0.2}
        panOpenMask={0.2}
        tweenHandler={(ratio) => ({
          main: { opacity: (2 - ratio) / 2 },
        })}
      >
        <View>
          <Text>Wut</Text>
        </View>
      </Drawer>
    );
    expect(wrapper.find('Text')).to.have.length(1);
  });
});
```

And here's the error print

```
/path-to-my-app/node_modules/react-native-drawer/index.js:1
(function (exports, require, module, __filename, __dirname) { import React, {
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/path-to-my-app/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (Drawer.js:6:1)
    at Module._compile (module.js:541:32)
    at loader (/path-to-my-app/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/path-to-my-app/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /path-to-my-app/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/path-to-my-app/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/path-to-my-app/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/path-to-my-app/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

Has someone got it working?

I tested with Node v4.x LTS and v6.2.1.
React is v15.1.0 and React Native v0.27.1.

**Comment by rt2zz** [comment]
Looks like you might need to babel transform your node modules. React native packager does this by default, but most other environments will not

**Comment by phil-a** [comment]
I'm getting a similar issue with trying to import another module, therefore it's not an issue with react-native-drawer.

**Comment by oriarditi** [comment]
As @phil-a said it's a common issue to all RN components when using mocha.
I wrap those components with low level components that won't import those components on load.
You can use something like this:

```
import React, { Component } from 'react';
import { StyleSheet } from 'react-native';

export default class MyDrawer extends Component {
  render() {
    const Drawer = require('react-native-drawer').default;
    return (
      <Drawer
        content={this.props.content}
        open={this.props.open}
        onClose={this.props.onClose}
        ...
        >
        {this.props.children}
      </Drawer>
    )
  }
}
```

**Comment by stami** [comment]
Oh, nice workaround! Thanks for tips, I'll consider this issue closed.
